# State list accessors
PLAYER_INPUT_INDX = 0
PLAYER_PREV_INPUT_INDX = 1
BALL_VELOCITY_INDX = 2
BALL_POSITION_INDX = 3
PADDLE_VELOCITY_INDX = 4
PADDLE_POSITION_INDX = 5
SCORE_PAUSE_TIMER_INDX = 6
CURRENT_STATE_INDX = 7
STATE_SWITCHED_INDX = 8
CURRENT_SCORE_INDX = 9

# game states
END_STATE = 0
PLAY_STATE = 1
SCORE_STATE = 2

PADDLE_WIDTH = 20
PADDLE_HEIGHT = 80
BALL_RADIUS = PADDLE_WIDTH

WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 800

CENTER_POINT = [WINDOW_WIDTH//2, WINDOW_HEIGHT//2]
CENTER_VERTICAL = WINDOW_HEIGHT//2
CENTER_HORIZONTAL = WINDOW_WIDTH//2

# Bounds for the paddle, they are set such that when the paddle is at the
# BOARD_TOP|BOTTOM_EDGE then the edge of the paddle touches the edge of the window.
# Therefore these are ideal values to use for bounding the paddle positions.
BOARD_WIDTH = WINDOW_WIDTH - 8*PADDLE_WIDTH
BOARD_HEIGHT = WINDOW_HEIGHT - PADDLE_HEIGHT

BOARD_LEFT_EDGE = (WINDOW_WIDTH - BOARD_WIDTH)//2
BOARD_RIGHT_EDGE = BOARD_LEFT_EDGE + BOARD_WIDTH
BOARD_TOP_EDGE = (WINDOW_HEIGHT - BOARD_HEIGHT)//2
BOARD_BOTTOM_EDGE = BOARD_TOP_EDGE + BOARD_HEIGHT

# Pause for two second after each score
PAUSE_DURATION = 500

MAX_SCORE = 10

# Per second speeds
SECOND_TO_FRAME = 1/60
BALL_INIT_SPEED = WINDOW_WIDTH/1.8
PADDLE_MAX_SPEED = WINDOW_WIDTH/50
PADDLE_BASE_SPEED = WINDOW_WIDTH/80
PADDLE_ACCEL = PADDLE_MAX_SPEED-PADDLE_BASE_SPEED

WHITE = (255,255,255)
BLACK = (0,0,0)

FONT_HEIGHT = PADDLE_HEIGHT*1.8
FONT_WIDTH = FONT_HEIGHT/1.8
FONT_STROKE = PADDLE_WIDTH
FONT_P1_X = CENTER_HORIZONTAL - FONT_WIDTH*3
FONT_P2_X = CENTER_HORIZONTAL + FONT_WIDTH*2
FONT_Y = 60
